### ISSUE TITLE
Docs for Basemap Styles (incl. raster)

### ISSUE THREAD

**Issue by mdmm13** [protomaps/docs#24]
Hey Brandon

Fantastic work with protomaps, really loving experimenting with it as an alternative to the hosted tile servers.

We're unfortunately stuck with raster tiles in Flutter for now (we're on flutter_map). Was wondering whether you might be able to say a few words around Basemap Styles (https://docs.protomaps.com/basemaps/styles) and the PMtiles model for raster? Found a few mentions in MapLibreGL and Leaflet, but nothing around styling.

Any input would be appreciated.

**Comment by bdon** [comment]
You could render vector tiles to raster via maplibre gl native or mapnik, but it is not efficient in general to store basemap raster tiles of the whole world, since many applications will want street-level detail beyond zoom 14/15, and image tiles stored down to 16+ are impractically large, as well as requiring regeneration on any style change + different pixel density resolution tiles. 

Rendering them on-the-fly from vector tiles is the best approach, but that is more amenable to a hosted service serving a handful of pre-designed map styles, I recommend https://www.thunderforest.com for this.

**Comment by mdmm13** [comment]
Thank you very much, appreciate the swift reply.
