### ISSUE TITLE
torrent

### ISSUE THREAD

**Issue by Lewiscowles1986** [protomaps/docs#8]
Would it make sense to have a torrent of the 100GB map file?

Using that I could seed (I'd limit connections to 5 and speed), but if enough folks offer, then it takes some bandwidth concern off your own servers.

**Comment by bdon** [comment]
There's nothing stopping you from seeding a version, but I haven't discovered a strong need for one now. Ways to get the file around faster without requiring a torrent client, and using plain HTTP:

* creating mirrors in geo-distributed locations
* implementing `pmtiles sync` to get a new file if you have an older copy

Parallel download tools like https://github.com/melbahja/got , axel and aria2 should also work fine with any download source, since those are based on HTTP Range Requests.

**Comment by Lewiscowles1986** [comment]
I'd talk about being a good network citizen and avoiding tooling such as `got`; which take up precious resources, but I feel like I'd be howling against the wind, so I'll close this. Thanks for answer.
