### ISSUE TITLE
add tilemaker on page pmtiles/create

### ISSUE THREAD

**Issue by Cyrille37** [protomaps/docs#87]
Hi,

Thanks for that fabulous tiles format, it's very very useful to host a single file behind a simple web server :heart_eyes: 

Perhaps [tilemaker](https://github.com/systemed/tilemaker/) has it's place on page [pmtiles/create](https://docs.protomaps.com/pmtiles/create). It permits to easily change how tiles are generated with a lua script (process.lua).

Tilemaker is missing the configuration for your [pmtiles shema](https://docs.protomaps.com/basemaps/layers) :disappointed: 

Regards & cheers.

**Comment by bdon** [comment]
Hi, I am hesitant to add that as one of the recommended tile generations because it currently does not create ordered (clustered) output, so the indexes are not as small as they could be. https://github.com/systemed/tilemaker/issues/653

maybe we add it with a note that it may not be ideal for large tilesets?

**Comment by Cyrille37** [comment]
Yes, a small note is a good idea.
Thanks.

**Comment by bdon** [comment]
Updated https://docs.protomaps.com/pmtiles/create

**Comment by Cyrille37** [comment]
Thanks @bdon :-)

Now I'm using the two steps generation: tilemaker generate the `mbtiles` then pmtiles cli convert to `pmtiles` like say in https://github.com/systemed/tilemaker/issues/653 because tilemaker is great with its LUA script for selecting data and encoding the schema.

Regards & cheers

**Comment by Cyrille37** [comment]
Hi @bdon 

Do you know a tilemaker's configuration (config.js+process.lua) that encode result as Protomap schema ?

Actually I've Openmaptiles & Shortbread schemas configuration but cannot find one for Protomap :-(

Thanks

**Comment by bdon** [comment]
I don't know of one, and I think it will be difficult because getting the correct-looking tiled output has a lot to do with things outside of the schema - for example, the simplification parameters and label dropping, which might make a Lua-profile output from Tilemaker look very different from the [java basemaps](https://github.com/protomaps/basemaps) profile.

So the focus is going to be on maintaining the Java profile for the Protomaps schema.

**Comment by Cyrille37** [comment]
You are right
Thanks
